### ISSUE TITLE
Talented does not open on Classic Era v230910-era

### ISSUE THREAD

**Issue by seathasky** [Lethay/TalentedClassic#112]
Talented does not open on Classic Era (on latest v230910-era)

Pressed N. Nothing happens.
Things ive tried: Turned off all addons. Still doesn't open. Deleted WTF saved variables for Talented, still doesn't open.

**Comment by spouddu** [comment]
Same problem. I even tried pressing the talents pane button between the spellbook and quest log buttons to no avail. Love the addon otherwise, begging for fixes.
Thanks

**Comment by Achewski** [comment]
Date: 2023-09-11 02:13:03
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Talented/talents.lua line 84:
   bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name Talented_Data. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable))
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: GetAddOnMetadata()
   [string "@Interface/AddOns/Talented/talents.lua"]:84:
      Interface/AddOns/Talented/talents.lua:83
   [string "@Interface/AddOns/Talented/talents.lua"]:94:
      Interface/AddOns/Talented/talents.lua:93
   [string "@Interface/AddOns/Talented/talents.lua"]:155: DataAddonLoaded()
   [string "@Interface/AddOns/Talented/talents.lua"]:198: GetTalentInfo()
   [string "@Interface/AddOns/Talented/viewmode.lua"]:55: UpdateCurrentTemplate()
   [string "@Interface/AddOns/Talented/core.lua"]:366: Update()
   [string "@Interface/AddOns/Talented/core.lua"]:350:
      Interface/AddOns/Talented/core.lua:347
   [string "=(tail call)"]: ?
   [string "TOGGLETALENTS"]:1:
      [string "TOGGLETALENTS"]:1
Locals:
(*temporary) = "down"
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6977 (SwimmingSeadragon)
  AIVoiceOver, v1.4.2
  AIVoiceOverDataVanilla, v0.1
  AtlasLootClassic, vv3.1.3
  AtlasLootClassicData, vv3.1.3
  AtlasLootClassicDungeonsAndRaids, vv3.1.3
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucScanData, v3.4.6908 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v10.1.7
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  ClassicFCT, vM0.87k
  CleanerLootMessages, v1.0.18
  ConsolePort, v2.6.16
  ConsolePortBar, v
  ConsolePortMenu, v
  ConsolePortWorld, v
  DejaClassicStats, v1404r001
  Details, v#Details.20230909.11902.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DropTheCheapestThing, vv2023.2
  DynamicCam, v2.4.3
  ElvUI, v13.40
  ElvUIBenikUI, v2.14
  ElvUILibraries, v13.40
  GatherMate2, v1.47.2-classic
  Guidelime, v3.040
  GuideLimeTUGsVanilla, v1.36
  Immersion, v1.4.27
  Informant, v3.4.6980 (SwimmingSeadragon)
  LeatrixMaps, v1.14.126
  LeatrixPlus, v1.14.126
  MacroToolkit, vv2.1.4
  MacroToolkitIcons, vv2.1.4
  Masque, v10.1.7
  MasqueRaeli, v27.2
  OPie, vYuzu 9+3.33
  OPieMasque, v10.1.7.0
  PallyPower, vv1.5.2-classic
  PetAbilities, v1.2.r20
  Plater, vPlater-v564.2-Classic
  Prat30, v3.9.36
  Prat30Libraries, v
  Quartz, v3.7.6
  Questie, v8.9.0
  RareScanner, v1.14.4.1
  Routes, vv1.7.4
  SexyMap, vv10.1.5
  Spy, v1.2.5
  Stubby, v3.4.6920 (SwimmingSeadragon)
  Talented, vv211114v
  TitanClassic, v1.3.3.11404
  TitanClassicAmmo, v1.3.3.11404
  TitanClassicBag, v1.3.3.11404
  TitanClassicClock, v1.3.3.11404
  TitanClassicGold, v1.3.3.11404
  TitanClassicLocation, v1.3.3.11404
  TitanClassicLootType, v1.3.3.11404
  TitanClassicMail, v2.51
  TitanClassicPerformance, v1.3.3.11404
  TitanClassicReagentTracker, v1.0.10.11304
  TitanClassicRegen, v1.3.3.11404
  TitanClassicRepair, v1.3.3.11404
  TitanClassicVolume, v1.3.3.11404
  TitanClassicXP, v1.3.3.11404
  TomTom, vv3.5.2-release
  TradeSkillMaster, vv4.13.14
  TradeSkillMasterAppHelper, vv4.13
  TurnIn, v2.2
  unitscan, vv1.1.4
  WeakAuras, v5.7.1
  WhatsTraining, v5.0.2
  ZeraTooltip, v2.9.0
  BlizRuntimeLib v1.14.4.51146(US) <enUS>
  (ck=9f1)

**Comment by Achewski** [comment]
I get this in swatter every time I try to open talents. I removed the section showing my addons so my comment isn't too big but can share my addons if it helps.


Date: 2023-09-11 02:13:03
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Talented/talents.lua line 84:
   bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name Talented_Data. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable))
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: GetAddOnMetadata()
   [string "@Interface/AddOns/Talented/talents.lua"]:84:
      Interface/AddOns/Talented/talents.lua:83
   [string "@Interface/AddOns/Talented/talents.lua"]:94:
      Interface/AddOns/Talented/talents.lua:93
   [string "@Interface/AddOns/Talented/talents.lua"]:155: DataAddonLoaded()
   [string "@Interface/AddOns/Talented/talents.lua"]:198: GetTalentInfo()
   [string "@Interface/AddOns/Talented/viewmode.lua"]:55: UpdateCurrentTemplate()
   [string "@Interface/AddOns/Talented/core.lua"]:366: Update()
   [string "@Interface/AddOns/Talented/core.lua"]:350:
      Interface/AddOns/Talented/core.lua:347
   [string "=(tail call)"]: ?
   [string "TOGGLETALENTS"]:1:
      [string "TOGGLETALENTS"]:1
Locals:
(*temporary) = "down"
(*temporary) = <function> defined =[C]:-1

**Comment by Lethay** [comment]
Fixed. Talented_Data was missing.

**Comment by seathasky** [comment]
> Fixed. Talented_Data was missing.

ty
