### ISSUE TITLE
Classic Era talent tooltips is missing for zhCN language

### ISSUE THREAD

**Issue by nedvedsk** [Lethay/TalentedClassic#116]
- I use the new version v230917,but there is still English tooltips in the game.
- when I only load talented addon,the bug is still.
![bug01](https://github.com/Lethay/TalentedClassic/assets/22416448/78f2d0f7-dbcb-4b0a-80e7-c55ef3010b37)
![bug02](https://github.com/Lethay/TalentedClassic/assets/22416448/b05dc4bb-9524-4d7f-831b-235c6261384b)

**Comment by Lethay** [comment]
Should now be working. Please let me know.

**Comment by nedvedsk** [comment]
> Should now be working. Please let me know.

not worked.

**Comment by nedvedsk** [comment]
3x Talented_Data/Locales/Talented_Data_zhCN.lua:42: attempt to index field '?' (a nil value)
[string "@Talented_Data/Locales/Talented_Data_zhCN.lua"]:42: in main chunk

Locals:
data = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
tree = <table> {
 numtalents = 16
 talents = <table> {
 }
 info = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
