### ISSUE TITLE
Dual Spec (1.15)

### ISSUE THREAD

**Issue by pattont** [Lethay/TalentedClassic#125]
While the addon does "work" when you have a spec selected, there is no options to show alternative spec and switch between them. You have to disable addon, switch specs, then reload addon, then apply template to that spec. 

It would be amazing if this addon added the activate button and showed the two spec tabs.

**Comment by jmckinney88** [comment]
An alternative workaround and a bit better than having to unload the addon is to make a macro with `/run SetActiveTalentGroup(3 - GetActiveTalentGroup())
`. Just throw that on your hotbars in the same place for each spec.

If you have the talented window open when switching specs though, it wont update until you close and reopen the window.

**Comment by pattont** [comment]
Thank you so much for this!!!
