### ISSUE TITLE
Broken w/ SOD P4

### ISSUE THREAD

**Issue by pattont** [Lethay/TalentedClassic#133]
![image](https://github.com/Lethay/TalentedClassic/assets/2903357/5a25d92a-24c1-48ad-bccc-f493673d7820)

![image](https://github.com/Lethay/TalentedClassic/assets/2903357/8dad7bb4-29a8-4f5c-b9d9-38f8b43b586e)

Talented window just won't come up with today's updates.

**Comment by deplex** [comment]
Change Line 71 in view.lua to `total = total + select(5, GetTalentTabInfo(i, ...)) ` and it will work again.

**Comment by Typhosy** [comment]
Spec do error to

1x Talented_SpecTabs/core.lua:36: attempt to compare string with number
[string "@Talented_SpecTabs/core.lua"]:36: in function <Talented_SpecTabs/core.lua:22>
[string "@Talented_SpecTabs/core.lua"]:102: in function `Update'
[string "@Talented_SpecTabs/core.lua"]:146: in function `Update'
[string "@Talented_SpecTabs/core.lua"]:188: in function <Talented_SpecTabs/core.lua:168>
[string "@Talented_SpecTabs/core.lua"]:207: in function `CreateBaseFrame'
[string "@Talented/core.lua"]:364: in function `Update'
[string "@Talented/core.lua"]:350: in function <Talented/core.lua:347>
[string "=(tail call)"]: ?
[string "TOGGLETALENTS"]:1: in function <[string "TOGGLETALENTS"]:1>

Locals:
info = <table> {
 tooltip = "Primary Talents"
 talentGroup = 1
 cache = <table> {
 }
}
pet = nil
talentGroup = 1
tabs = 3
imax = 0
min = 0
max = 0
total = 0
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
cache = <table> {
 points = ""
 icon = "Balance"
 name = 283
}
name = 283
icon = "Balance"
points = ""
(*temporary) = 283
(*temporary) = "Balance"
(*temporary) = "attempt to compare string with number"

**Comment by pattont** [comment]
> Change Line 71 in view.lua to `total = total + select(5, GetTalentTabInfo(i, ...)) ` and it will work again. (tested only on classic era)

That allows you to see your spec, but doesn't actually fix the two tabs on the right
