### ISSUE TITLE
Update on CurseForge Possible?

### ISSUE THREAD

**Issue by PicklePriest** [Lethay/TalentedClassic#135]
I've seen there have been fixes to the recent SoD P4 changes and its effects to Era as well. I unfortunately am quite clueless about understanding how to fix this myself even though it's laid out here, I do not understand how I translate that to editing my files myself.

So unless someone can do screenshots step by step, is there going to be an updated version on Curseforge soon? <3

**Comment by Lethay** [comment]
Now updated. Thank you.
