### ISSUE TITLE
Classic Era broken 1.15.4.56760

### ISSUE THREAD

**Issue by GeorgeChatzigiannis** [Lethay/TalentedClassic#140]
Actions or Templates options are inaccessible.

10x Talented/ui/menu.lua:448: attempt to call global 'EasyMenu' (a nil value)
[string "@Talented/ui/menu.lua"]:448: in function OpenTemplateMenu
[string "@Talented/ui/base.lua"]:143: in function <Talented/ui/base.lua:142>

**Comment by Venomisto** [comment]
Patch fix for now, could maybe break if they remove more of the old menu stuff in the future.
Add this in Talented/ui/menu.lua at line 447.ua (just has to be above the first EasyMenu() call.

local function EasyMenu_Initialize( frame, level, menuList )
	for index = 1, #menuList do
		local value = menuList[index]
		if (value.text) then
			value.index = index;
			UIDropDownMenu_AddButton( value, level );
		end
	end
end

local function EasyMenu(menuList, menuFrame, anchor, x, y, displayMode, autoHideDelay )
	if ( displayMode == "MENU" ) then
		menuFrame.displayMode = displayMode;
	end
	UIDropDownMenu_Initialize(menuFrame, EasyMenu_Initialize, displayMode, nil, menuList);
	ToggleDropDownMenu(1, nil, menuFrame, anchor, x, y, menuList, nil, autoHideDelay);
end

**Comment by gotmilk0112** [comment]
Yeh, that seems to work. The little menus in the addon are working again.

**Comment by Lethay** [comment]
Thank you for this, I patched it in
