### ISSUE TITLE
The "Apply template" button does not work.

### ISSUE THREAD

**Issue by chkmyid** [Lethay/TalentedClassic#19]
Other users, including myself, could not apply the template to the same bug.
The template has not been applied when the "Apply template" button is pressed.

And the Talented message was printed on the chat frame as shown below.
> Talented: Nothing to do

The level to which the template is applied has this bug at 60 levels and all levels below.
This problem does not work even though there are remaining talent points.

**Comment by Lethay** [comment]
I have a potential fix. Just waiting until I level up again to test it. I can't test that it works with all 51 talent points / after resetting talents, because I am dirt poor. But hopefully it works!

**Comment by chkmyid** [comment]
Excellent! I hope to be able to introduce the problem-solved version to Korean users as soon as possible.

Thank you for your hard work.

**Comment by Lethay** [comment]
How are you "introducing" the problem-solved version...?

**Comment by chkmyid** [comment]
Posted on a specialized portal site in Korea's famous World of Warcraft. hehe ;-)

**Comment by Lethay** [comment]
Ah, I guessed as much. If you haven't done so, please also provide credit to Jerry, the original author!
