### ISSUE TITLE
Taiwanese localisation (spell tooltips)

### ISSUE THREAD

**Issue by class2u** [Lethay/TalentedClassic#20]
Thank you for making this great addon. Is there any possible to show localized talent data for spell name and description in tooltips. I am using zhTW client.

I saw another addon alaTalentEmu can do this. But I like yours more. :)

**Comment by Lethay** [comment]
Hi, I'm sorry, I can't do this myself because the tooltips need to be exported from the Taiwanese client, which I don't have. If you'd like to do it yourself, please see the script in the Talented_Data_Export folder.

**Comment by class2u** [comment]
Thank you. It is a great tool for exporting data. I am working on it.

**Comment by class2u** [comment]
Done! Here are [Talented_Data_zhTW.lua and zhTW.lua](https://drive.google.com/file/d/1Br56o27TH-hXCKH3ioCkrtWB6H7wIeim/view?usp=sharing) I modified some for better translation.

**Comment by Lethay** [comment]
Thank you for this! I have now added them to the repository and Curseforge.
