### ISSUE TITLE
I still found that the "Apply template" menu was not working properly.

### ISSUE THREAD

**Issue by chkmyid** [Lethay/TalentedClassic#24]
I have created a template up to 39 levels.
Applying the template to a 32 level character with no remaining points will output a message in the chat frame, "Sorry, I can't apply this template because you don't have enough points available (need 7)."
When 33 levels are given 1 point, click the Apply Template menu, and the remaining 1 point will not be used and the same message will be printed.

My guess is to use the remaining 1 point and output it to the chat frame, "Error while applying talents! Not enough talent points!" or "Sorry, I can't apply this template because you don't have enough talent points available (need 6)!"

I still found that the "Apply template" menu was not working properly.

**Comment by Lethay** [comment]
Hi, this behaviour seems correct to me! The "Apply template" function is not meant to learn individual talents, as the behaviour could result in unpleasant "surprises" if someone did not anticipate the order in which talents are learnt.
If you want to learn individual talents, please click that Talent in the view of your current build! You can also set a template as a "target" so that you can compare it with your current build.

**Comment by chkmyid** [comment]
I just took an example as a point, but if you don't use the remaining points at any level and the template you created after initializing talent doesn't work, you might see an add-on problem. This is a feature that's been used for a long time. Talented is not an addon that can only be used at level 60.

**Comment by Lethay** [comment]
No, indeed. I primarily use Talented for levelling, not at max level. But I learn talents individually each time I level up by clicking the one I want: that's not what "Apply Template" is for. If you used it each time you levelled up, it would always pick the left tree first, and the left column of any row first. That might not be desirable.

I'm not sure what you're referring to when you say "template you created after initialising talent doesn't work". What problems would occur? If there's not enough talent points, "Apply Template" does nothing.
