### ISSUE TITLE
Simplified Chinese localisation

### ISSUE THREAD

**Issue by rainyr** [Lethay/TalentedClassic#25]
[Talented_Data_zhCN.zip](https://github.com/Lethay/TalentedClassic/files/3714687/Talented_Data_zhCN.zip)

**Comment by Lethay** [comment]
Hi, thanks very much for this work. The files were not in the right format, but I did the last bit of work for you. I have now added them to the repository and Curseforge. Please let me know if they are working correctly.

**Comment by rainyr** [comment]
they are working correctly.
