### ISSUE TITLE
Error on initial opening of UI (/reload fixes issue for that session)

### ISSUE THREAD

**Issue by Lanzlo** [Lethay/TalentedClassic#32]
Date: 2019-11-14 14:15:40
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Talented\encode.lua line 166:
   attempt to index field '?' (a nil value)
Debug:
   Talented\encode.lua:166: StringToTemplate()
   Talented\encode.lua:260: UnpackTemplate()
   Talented\encode.lua:266: CopyPackedTemplate()
   Talented\core.lua:35: MakeTarget()
   Talented\core.lua:245: SetTemplate()
   Talented\core.lua:334: Update()
   Talented\core.lua:323:
      Talented\core.lua:320
   (tail call): ?
   [string "TOGGLETALENTS"]:1:
      [string "TOGGLETALENTS"]:1
Locals:
self = <table> {
 CreateTemplateMenu = <function> defined @Interface\AddOns\Talented\ui\menu.lua:65
 defaults = <table> {
 }
 LoadAddOn = <function> defined @Interface\AddOns\Talented\core.lua:66
 OpenOptionsFrame = <function> defined @Interface\AddOns\Talented\ui\menu.lua:26
 MakeArrow = <function> defined @Interface\AddOns\Talented\ui\arrows.lua:17
 GetTalentPrereqs = <function> defined @Interface\AddOns\Talented\spell.lua:234
 spelldata = <table> {
 }
 UnregisterComm = <function> defined @Interface\AddOns\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 HideTooltipInfo = <function> defined @Interface\AddOns\Talented\tips.lua:134
 DataAddonLoaded = <function> defined @Interface\AddOns\Talented\talents.lua:151
 GetDefaultMode = <function> defined @Interface\AddOns\Talented\core.lua:260
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 UpdateTemplateName = <function> defined @Interface\AddOns\Talented\core.lua:115
 LoadTemplates = <function> defined @Interface\AddOns\Talented\core.lua:339
 GetMode = <function> defined @Interface\AddOns\Talented\core.lua:46
 SetTemplate = <function> defined @Interface\AddOns\Talented\core.lua:239
 SetMode = <function> defined @Interface\AddOns\Talented\core.lua:50
 RegisterMessage = <function> defined @Interface\AddOns\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface\AddOns\Talented\core.lua:330
 hooks = <table> {
 }
 SendCommMessage = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Libs\AceHook-3.0\AceHook-3.0.lua:274
 OpenTemplate = <function> defined @Interface\AddOns\Talented\core.lua:221
 OnEnable = <function> defined @Interface\AddOns\Talented\core.lua:264
 GetTemplateStringClass = <function> defined @Interface\AddOns\Talented\encode.lua:15
 MakeButton = <function> defined @Interface\AddOns\Talented\ui\buttons.lua:75
 ImportTemplate = <function> defined @Interface\AddOns\Talented\core.lua:199
 Pool = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\Talented\core.lua:70
 UnregisterAllEvents = <function> defined @Interface\AddOns\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 base = TalentedFrame {
 }
 Deserialize = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\AceSerializer-3.0\AceSerializer-3.0.lua:246
 MakeActionMenu = <function> defined @Interface\AddOns\Talented\ui\menu.lua:363
 TalentView = <table> {
 }
 GetName = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 views = <table> {
 }
 name = "Talented"
 UpdateView = <function> defined @Interface\AddOns\Talented\viewmode.lua:90
 GetTalentInfo = <function> defined @Interface\AddOns\Talented\talents.lua:195
 Disable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetOption = <function> defined @Interface\AddOns\Talented\options.lua:62
 Unhook = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Interface\AddOns\Talented\core.lua:6
 UncompressSpellData = <function> defined @Interface\AddOns\Talented\spell.lua:96
 SetOption = <function> defined @Interface\AddOns\Talented\options.lua:55
 UpdateCurrentTemplate = <function> defined @Interface\AddOns\Talented\viewmode.lua:44
 Serialize = <function> defined @Interface\AddOns\ClassicThreatMeter\lib\AceSerializer-3.0\AceSerializer-3.0.lua:122
 Debug = <function> defined @Interface\AddOns\Talented\core.lua:14
 EnableUI = <function> defined @Interface\AddOns\Ta
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.57
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  auccheapsearcher, v20191013-retail
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Bejeweled, v1.13.2
  CallbackHandler10, v
  ClassicQuestLog, v1.4.5-Classic
  ClassicAuraDurations, v
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.10
  Clique, vv1.0.3-classic
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMRaidLeadTools, vr124
  DBMSMGEventsPack, v1.5.3
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r037
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtTabardUI, v1.0.0
  GSE, v2.4.23
  GSEGUI, v2.4.23
  GSELDB, v2.4.23
  GuildRosterManager, v1.831
  Informant, v8.2.6374 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LibStub, v
  Necrosis, v5.2
  NugEnergy, v1.13.11
  OmniCC, v8.2.5
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.2.1
  RCLootCouncilClassic, v0.3.1
  RealMobHealth, v2.13
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SimplyGInv, v1.13.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Talented, vv191112
  TalentedData, v
  TalentedDataExport, v1.0
  TinyTooltip, v8.2.1
  TitanClassic, v1.1.3.11302
  TitanClassicAmmo, v1.1.3.11302
  TitanClassicBag, v1.1.3.11302
  TitanClassicClock, v1.1.3.11302
  TitanClassicGold, v1.1.3.11302
  TitanClassicLocation, v1.1.3.11302
  TitanClassicLootType, v1.1.3.11302
  TitanClassicPerformance, v1.1.3.11302
  TitanClassicRegen, v1.1.3.11302
  TitanClassicRepair, v1.1.3.11302
  TitanClassicVolume, v1.1.3.11302
  TitanClassicXP, v1.1.3.11302
  TomTom, vv11302-1.0.8
  totalRP3, v1.6.7.1
  totalRP3Data, v
  TrinketMenu, v7.3.2
  VendorMaster, v1.3
  VendorPrice, v1.2.9
  WeaponSwingTimer, v4.1.0
  WIM, v3.8.3
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=99b)

**Comment by Lethay** [comment]
This one is even more confusing. The line that gives the error is one that checks whether the number of the talent we're about to check is longer than the ones that actually exist in the talent tree. In other words, it does something with talent 1, then talent 2, then talent 3, etc. If there are only 20 talents in the tree, it stops doing anything before checking "talent 21". Here, it fails because the number of talent trees is detected to be 0, or else one of the trees is empty. But this is your current template, so that shouldn't happen.

Again, because I don't have this problem, I can't really pin down why it's happening.
What locale are you using (enUS, deDE, etc)?

**Comment by Lanzlo** [comment]
I am using enUS.

**Comment by Lethay** [comment]
That removes one possibility for the cause of the crash. It makes me very difficult for me to help you, because I don't have the problem.
- Is Talented_Data installed and loaded?
- Do you have any templates saved/stored?
- Does the problem persist if you delete and reinstall the addon?
- Does the problem persist if you delete config/storage files for the addon?
- Does the problem persist if all other addons are disabled? If so, which addon(s) make the problem come back?

**Comment by Lanzlo** [comment]
OK, reinstalled, and didn't do anything.

Deleted the storage/configs... that worked.

**Comment by Lethay** [comment]
Good to hear. Let me know if it reoccurs, it'd then be good to see what your configs were.

**Comment by roweboy1974** [comment]
What storage/config files are you referring to?
