### ISSUE TITLE
Error on Options

### ISSUE THREAD

**Issue by Lanzlo** [Lethay/TalentedClassic#33]
Date: 2019-11-14 16:39:50
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Talented\ui\menu.lua line 27:
   Talented isn't registed with AceConfigRegistry, unable to open config
Debug:
   [C]: ?
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1861: Open()
   Talented\ui\menu.lua:27: OpenOptionsFrame()
   Talented\ui\menu.lua:344: func()
   ..\FrameXML\UIDropDownMenu.lua:958: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "Talented isn't registed with AceConfigRegistry, unable to open config"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.57
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  auccheapsearcher, v20191013-retail
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Bejeweled, v1.13.2
  CallbackHandler10, v
  ClassicQuestLog, v1.4.5-Classic
  ClassicAuraDurations, v
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.10
  Clique, vv1.0.3-classic
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMRaidLeadTools, vr124
  DBMSMGEventsPack, v1.5.3
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r037
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtTabardUI, v1.0.0
  GSE, v2.4.23
  GSEGUI, v2.4.23
  GSELDB, v2.4.23
  GuildRosterManager, v1.831
  Informant, v8.2.6374 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LibStub, v
  Necrosis, v5.2
  NugEnergy, v1.13.11
  OmniCC, v8.2.5
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.2.1
  RCLootCouncilClassic, v0.3.1
  RealMobHealth, v2.13
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SimplyGInv, v1.13.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Talented, vv191112
  TalentedData, v
  TalentedDataExport, v1.0
  TinyTooltip, v8.2.1
  TitanClassic, v1.1.3.11302
  TitanClassicAmmo, v1.1.3.11302
  TitanClassicBag, v1.1.3.11302
  TitanClassicClock, v1.1.3.11302
  TitanClassicGold, v1.1.3.11302
  TitanClassicLocation, v1.1.3.11302
  TitanClassicLootType, v1.1.3.11302
  TitanClassicPerformance, v1.1.3.11302
  TitanClassicRegen, v1.1.3.11302
  TitanClassicRepair, v1.1.3.11302
  TitanClassicVolume, v1.1.3.11302
  TitanClassicXP, v1.1.3.11302
  TomTom, vv11302-1.0.8
  totalRP3, v1.6.7.1
  totalRP3Data, v
  TrinketMenu, v7.3.2
  VendorMaster, v1.3
  VendorPrice, v1.2.9
  WeaponSwingTimer, v4.1.0
  WIM, v3.8.3
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=9c8)

**Comment by Lethay** [comment]
Does this one only happen after one of the other two errors happens?

**Comment by Lanzlo** [comment]
This happens after the initial errors I listed.

**Comment by Lethay** [comment]
I thought so. It's because the addon crashes before it initialises, and so doesn't register its options.
