### ISSUE TITLE
Import from Inspect

### ISSUE THREAD

**Issue by Sigma88** [Lethay/TalentedClassic#38]
I remember using this addon way back when, probably WotLK

and I remember that there was a very useful feature that would save any build from inspected players. I think the builds saved from inspecting players were only temporarily stored and lost at every relog

still that was enough for me to quickly inspect someone and then look at their talents later 

and I could always decide to save the build in the non-temporary list

Do you think this feature would be possible in classic as well?

**Comment by Lethay** [comment]
Hi,

Unfortunately not, because you can't inspect talents in classic. I'd need
to code the communication myself and both players would have to have
Talented. Wait for TBC!

**Comment by Sigma88** [comment]
Makes sense.

Thank you anyways!
