### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Zephryl87** [Lethay/TalentedClassic#43]
Date: 2020-10-03 14:06:32
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Talented\editmode.lua line 109:
   bad argument #1 to 'ipairs' (table expected, got nil)
Debug:
   [C]: ?
   Talented\editmode.lua:109: ValidateTemplate()
   Talented\core.lua:468: LoadTemplates()
   Talented\core.lua:81:
      Talented\core.lua:78
   [C]: ?
   ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:623:
      ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:615
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Ace3, v
  AceGUI30SFXWidgets, v1.0.1
  Aptechka, v1.13.62
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AtlasQuest, v4.11.66
  ATTClassic, v0.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoLoggerClassic, vv1.3-release
  BasicMinimap, vv3-classic
  BCT, v1.37
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.3
  BetterVendorPrice, vv1.13.06
  BijouRR, v1.1.6
  Capping, vv4-classic
  CharacterStatsClassic, v3.6.3
  CharacterTooltip, v1.0.4
  ClassicSpellActivations, v
  DBMCore, v1.13.60
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.3.12
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  EavesDrop, v1.0.0
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FADEWorldTimers, v1.0
  FastGuildInvite, v76
  FreeRefills, v116
  GroupCalendar, v
  GuildRosterManager, v1.895
  Guildbook, v2.3.4
  Hemlock, v1.1.3
  honorspy, v1.7.7
  ItemRack, v
  LeatrixMaps, v1.13.80
  LibStub, v
  LootReserve, v2020-09-10
  Masque, v8.3.1
  MasqueApathy, v8.3.2
  MasqueCaith, v8.3.2
  MasqueCirque, v8.3.1
  MasqueEntropy, v8.3.2
  MasqueSerenity, v8.3.2
  MBB, v1.1.1
  MissingTradeSkillsList, v1.13.51
  MoreItemStats, v1.2.4
  NovaWorldBuffs, v1.81
  OmniCC, v8.3.6
  Peggle, v2.2.8
  PerfectDominanceLootPriority, v1.0
  PowerRaid, v3.2.4
  Prat30, v3.8.26
  Prat30Libraries, v
  Prio3, v20200827
  Quartz, v3.5-classic-5
  Questie, v6.0.5
  RaidHelper, v
  RollTrackerClassic, v2.21
  SafeQueue, vv3.6
  ScepCalendar, v0.1a
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.1.2
  statweightsclassic, v
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Talented, vv200804
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=8c9)

**I don't know, why this is happening.. tried reinstalling the addon, but it didn't help either..
If I then try to open the talents I get another error:**

Date: 2020-10-03 14:08:11
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Talented\view.lua line 95:
   attempt to index local 'first_tree' (a nil value)
Debug:
   [C]: ?
   Talented\view.lua:95: SetClass()
   Talented\view.lua:157: SetTemplate()
   Talented\core.lua:269: SetTemplate()
   Talented\core.lua:361: Update()
   Talented\core.lua:346:
      Talented\core.lua:343
   (tail call): ?
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Ace3, v
  AceGUI30SFXWidgets, v1.0.1
  Aptechka, v1.13.62
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AtlasQuest, v4.11.66
  ATTClassic, v0.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoLoggerClassic, vv1.3-release
  BasicMinimap, vv3-classic
  BCT, v1.37
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.3
  BetterVendorPrice, vv1.13.06
  BijouRR, v1.1.6
  Capping, vv4-classic
  CharacterStatsClassic, v3.6.3
  CharacterTooltip, v1.0.4
  ClassicSpellActivations, v
  DBMCore, v1.13.60
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.3.12
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  EavesDrop, v1.0.0
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FADEWorldTimers, v1.0
  FastGuildInvite, v76
  FreeRefills, v116
  GroupCalendar, v
  GuildRosterManager, v1.895
  Guildbook, v2.3.4
  Hemlock, v1.1.3
  honorspy, v1.7.7
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.80
  LibStub, v
  LootReserve, v2020-09-10
  Masque, v8.3.1
  MasqueApathy, v8.3.2
  MasqueCaith, v8.3.2
  MasqueCirque, v8.3.1
  MasqueEntropy, v8.3.2
  MasqueSerenity, v8.3.2
  MBB, v1.1.1
  MissingTradeSkillsList, v1.13.51
  MoreItemStats, v1.2.4
  NovaWorldBuffs, v1.81
  OmniCC, v8.3.6
  Peggle, v2.2.8
  PerfectDominanceLootPriority, v1.0
  PowerRaid, v3.2.4
  Prat30, v3.8.26
  Prat30Libraries, v
  Prio3, v20200827
  Quartz, v3.5-classic-5
  Questie, v6.0.5
  RaidHelper, v
  RollTrackerClassic, v2.21
  SafeQueue, vv3.6
  ScepCalendar, v0.1a
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.1.2
  statweightsclassic, v
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Talented, vv200804
  TalentedData, v
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  TitanSocial, v1.13.3
  TomTom, vv11305-1.1.4
  TradeSkillMaster, vv4.10.6
  WeakAuras, v2.18.4
  WeaponSwingTimer, v4.1.0
  WideQuestLog, v
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=b2e)

**Comment by Lethay** [comment]
I noticed that you didn't have Talented_Data activated in your first error, which might've been the problem. When you reinstalled it, did you also wipe the config files for Talented?

**Comment by Zephryl87** [comment]
That's weird, because it definitely is activated.. oO
Should I delete it and install again?
Also, do I lose my builds, if i delete the config files? I assume not, but I want to make sure xD

**Comment by Lethay** [comment]
Ah, you fixed it. Sorry, I wanted to tell you that deleting that WOULD wipe your builds - the backup would've been to export them.
Yes, I changed the formatting of the templates, so that templates for different classes could be saved with the same name (e.g. you can make a "Tank" build for both warrior and druid now). There was supposed to be a function that automatically converts old data to the new type. Did it perhaps not work for some reason...? It would've been nice to have your config files before you deleted them so I could see what went wrong, but I suppose it's too late now.
