### ISSUE TITLE
TBC talents export links to classic Wowhead

### ISSUE THREAD

**Issue by ruudvanstrijp** [Lethay/TalentedClassic#46]
When you export talents, the URL that's being generated is as in this example:
http://classic.wowhead.com/talent-calc/mage/23000300000000000000000-0000000000000000000000-0535320310035010001551-
This goes to a classic 31-talents deep tree.

It should be pointing towards tbc.wowhead.com instead:
http://tbc.wowhead.com/talent-calc/mage/23000300000000000000000-0000000000000000000000-0535320310035010001551-

**Comment by Lethay** [comment]
Thanks. I have this fixed locally, but was waiting for another change (like localisation) before committing.
