### ISSUE TITLE
Exporting a template from TBC leads to wowhead classic and causes issues

### ISSUE THREAD

**Issue by wheatbread** [Lethay/TalentedClassic#48]
Hi!

When exporting a template from TBC in-game, the URL leads to classic.wowhead etc. instead of tbc.classic etc.  This results in the classic template appearing on the page and the talents appearing all misplaced on it.

**Comment by Lethay** [comment]
Thanks, but it's fixed with the latest version, as of an hour ago. You have very bad timing :P
