### ISSUE TITLE
1.14 SetBackdrop issue

### ISSUE THREAD

**Issue by Slivo-fr** [Lethay/TalentedClassic#53]
Hi, the classic ERA or vanilla version must be updated with BC / SL new backdrop mechanics.
The talent frame doesn't show up at all at the moment

Lua error bellow

1x Talented\ui\base.lua:310: attempt to call method 'SetBackdrop' (a nil value)
[string "@Talented\ui\base.lua"]:310: in function `CreateBaseFrame'
[string "@Talented\core.lua"]:359: in function `Update'
[string "@Talented\core.lua"]:347: in function <Talented\core.lua:344>
[string "=(tail call)"]: ?
[string "TOGGLETALENTS"]:1: in function <[string "TOGGLETALENTS"]:1>

Locals:
self = <table> {
 CreateTemplateMenu = <function> defined @Talented\ui\menu.lua:65
 defaults = <table> {
 }
 LoadAddOn = <function> defined @Talented\core.lua:74
 OpenOptionsFrame = <function> defined @Talented\ui\menu.lua:26
 MakeArrow = <function> defined @Talented\ui\arrows.lua:17
 GetTalentPrereqs = <function> defined @Talented\spell.lua:234
 UnregisterComm = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 HideTooltipInfo = <function> defined @Talented\tips.lua:134
 DataAddonLoaded = <function> defined @Talented\talents.lua:151
 GetDefaultMode = <function> defined @Talented\core.lua:284
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 UpdateTemplateName = <function> defined @Talented\core.lua:123
 GetMode = <function> defined @Talented\core.lua:54
 SetTemplate = <function> defined @Talented\core.lua:263
 SetMode = <function> defined @Talented\core.lua:58
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Talented\core.lua:358
 hooks = <table> {
 }
 SendCommMessage = <function> defined @DataStore\libs\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 UnregisterAllComm = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Broker_MoneyFu\Libs\AceHook-3.0\AceHook-3.0.lua:274
 OpenTemplate = <function> defined @Talented\core.lua:244
 OnEnable = <function> defined @Talented\core.lua:288
 GetTemplateStringClass = <function> defined @Talented\encode.lua:15
 MakeButton = <function> defined @Talented\ui\buttons.lua:75
 ImportTemplate = <function> defined @Talented\core.lua:209
 Pool = <table> {
 }
 UnregisterAllEvents = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 optionsFrame = <unnamed> {
 }
 Deserialize = <function> defined @DataStore\libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 MakeActionMenu = <function> defined @Talented\ui\menu.lua:368
 TalentView = <table> {
 }
 GetName = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 views = <table> {
 }
 name = "Talented"
 UpdateView = <function> defined @Talented\viewmode.lua:90
 GetTalentInfo = <function> defined @Talented\talents.lua:195
 Disable = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetOption = <function> defined @Talented\options.lua:65
 Unhook = <function> defined @Broker_MoneyFu\Libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Talented\core.lua:7
 UncompressSpellData = <function> defined @Talented\spell.lua:96
 SetOption = <function> defined @Talented\options.lua:58
 UpdateCurrentTemplate = <function> defined @Talented\viewmode.lua:44
 Serialize = <function> defined @DataStore\libs\AceSerializer-3.0\AceSerializer-3.0.lua:122
 Debug = <function> defined @Talented\core.lua:15
 EnableUI = <function> defined @Talented\ui\base.lua:362
 MakeTalentFrame = <function> defined @Talented\ui\trees.lua:99
 RegisterComm = <function> defined @DataStore\libs\AceComm-3.0\AceComm-3.0.lua:60
 PLAYER_TALENT_UPDATE = <function> defined @

**Comment by Lethay** [comment]
Fixed!

**Comment by Slivo-fr** [comment]
Thanks !

You however didn't release the fix for 1.14.1

**Comment by Slivo-fr** [comment]
@Lethay ⬆️

**Comment by Lethay** [comment]
To clarify, you just mean that the addon's expected version hasn't been set to 1.14.1, right? Because that doesn't matter, the addon just works anyway. I'm on holiday at the moment and can't check myself.

**Comment by Lethay** [comment]
Or do you mean you don't see the updated version on Curse? Because I uploaded it there for some version of Classic-SoM a few weeks ago.

**Comment by Slivo-fr** [comment]
Yeah the update didn't show up 

![image](https://user-images.githubusercontent.com/10325988/144743110-b88bb2f9-3007-4daa-a399-db698392961d.png)

I run a modified version to fix backdrop on my own and I missed the previous release it seems.
Apologies we good then ! 

Thanks for your work :)
