### ISSUE TITLE
inccrect version number in latest TBC update

### ISSUE THREAD

**Issue by MyTechnoHunter** [Lethay/TalentedClassic#56]
toc file still uses 20501 in the addon.. if its working (and it seems to work fine) can you please update the toc file to use 20502 as the game version is?
thanks

**Comment by Lethay** [comment]
Thanks, I didn't notice. It is indeed working, the version number doesn't matter other than for alerting players of out-of-date addons.

**Comment by MyTechnoHunter** [comment]
sounds good, thanks!

**Comment by Lethay** [comment]
Fixed
