### ISSUE TITLE
TlanetedClassic Data Chinese Localization

### ISSUE THREAD

**Issue by maxevil05** [Lethay/TalentedClassic#59]
this is Chinese Localization for talented Classic Data，please check the file， thanks！
[Talented_Data_zhCN.zip](https://github.com/Lethay/TalentedClassic/files/7681587/Talented_Data_zhCN.zip)

**Comment by Lethay** [comment]
Thank you. Sorry that it took me a while to do this, I forgot about it. It should now be in the game. If you still play, please let me know if it works.
