### ISSUE TITLE
Add support for WowUp

### ISSUE THREAD

**Issue by jimsimon** [Lethay/TalentedClassic#60]
CurseForge/Overwolf has blocked WowUp from accessing files hosted on its server. Please consider also publishing to WoWInterface or WowUpHub: https://wowup.io/guide/wowup/hub

**Comment by Lethay** [comment]
Yes, absolutely, thanks for the guide. I am snowed under with my paid work, but I will do this at the first opportunity - maybe this weekend.

**Comment by jimsimon** [comment]
Another option is to publish to Wago. I've heard that they pay addon authors too. :)

**Comment by Lethay** [comment]
Now released on wago.io and I've given the release link to the WowUp authors. That'll take a little bit to be manually approved, apparently. I'll check back on it later.
