### ISSUE TITLE
API calls to get talent string and apply talent string

### ISSUE THREAD

**Issue by TimothyLuke** [Lethay/TalentedClassic#61]
Hi All,

I have an unusual request.  I develop a mod that creates advanced macros. For retail I store which talents have been selected etc but for Classic I want to do this but currently don’t. Rather than reinventing the wheel want to use Talented as an optional requirement.

What I would like to be able to do is query talented by an API call to get the currently applied talents as a talented string and then another call to talented to import and it apply a supplied talent string.

eg is there something like the following that I can do in Lua.
local Talented = Talented
If Talented then
  TalentString = Talented.getCurrentTalentString()
end

**Comment by Lethay** [comment]
Sorry that I never got back to you on this. Talented now does this via calling spellIDs, which you could hopefully also do. Will close, as this is more relevant to the TBC version

**Comment by TimothyLuke** [comment]
My mod has a box where in Retail it stores 122131 where they are the rows and columns,  currently for Classic it simply stores “Wrath Classic” in the box.  What I l would like would be to detect if Talented is installed then store the https://wowhead.com/talent-calculator…… link that Talented creates and then add a button that someone could import that template to Talented.

BTW I added a pull request to fix the link to use the Wrath talent calculator rather than the TBC one.

TimothyLuke

**Comment by Lethay** [comment]
Aha! Yes you did, but I got to it myself in my round of edits last night 😅.
Anyway, a quick function that may work for this:

`
current_spec = 
Talented.exporters[L["Wowhead Talent Calculator"]](Talented, 
`

**Comment by TimothyLuke** [comment]
Ok found a Race condition.  If the Talented window is never opened, then Talented.alternates[] is never populated and is nil.  Is there an init/setup function I can call to get this to populate?


Also got the following missing L[] entry:
```
1x AceLocale-3.0-6: Talented: Missing entry for 'https://www.wowhead.com/wotlk/talent-calc/%s/%s'
[string "@Talented\wowhead.lua"]:66: in function `?'
[string "=[C]"]: in function `RunScript'
[string "@FrameXML\ChatFrame.lua"]:2196: in function `?'
[string "@FrameXML\ChatFrame.lua"]:4933: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4596: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4632: in function <FrameXML\ChatFrame.lua:4628>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```

**Comment by TimothyLuke** [comment]
Found it - Talented:UpdatePlayerSpecs() -- cheers for the help

**Comment by Lethay** [comment]
You're welcome - for what little I did. I'm sorry that I didn't help very much - I'm afraid I was a bit swamped with tasks to get this up and running for Wrath, for what little time I had to develop.

**Comment by TimothyLuke** [comment]
I understand that totally.  

If you are curious this was the result: https://github.com/TimothyLuke/GSE-Advanced-Macro-Compiler/issues/1156 https://github.com/TimothyLuke/GSE-Advanced-Macro-Compiler/commit/770143430f9da315ebd77bbebdd6144b28cb606f
