### ISSUE TITLE
[Suggestion] Talented Classic Lite version

### ISSUE THREAD

**Issue by Nillx** [Lethay/TalentedClassic#66]
I love how the addon looks but i cant get used to the options for the addon. Wish there was a Lite version that works like Blizz's talents but looks like Talented without the extra options/templates and sharing options.

**Comment by Lethay** [comment]
That'd be nice, but I won't do it - I work full-time and this is just something I do for a part of my free time. You're welcome to do it, if you know Lua.

**Comment by Nillx** [comment]
I understand thanks for the answer.
