### ISSUE TITLE
WOTLK - Death Knight Talent Support

### ISSUE THREAD

**Issue by maximus210793** [Lethay/TalentedClassic#70]
Hi,
can you add support for WOTLK Death Knights Talents please?
Thanks a lot..

**Comment by Lethay** [comment]
As far as I know, this is already supported. What are you seeing?

**Comment by Darangen** [comment]
I get the same problem.

**Comment by Lethay** [comment]
How did you install the addon? The deathknight talents are literally there, so I'm not sure what to say. However, I have seen multiple reports of this problem. It seems to me like one or more of the repositories (like Curse or WoWUp) are not updating Talented_Data.
![image](https://user-images.githubusercontent.com/5658454/188278567-6c55c00e-262b-4ba7-886b-d30fd8e05145.png)

**Comment by Dana-Ferguson** [comment]
![image](https://user-images.githubusercontent.com/7284858/188453256-30142e6c-2785-4b63-86bb-31ce60f0da44.png)

Looks like the culprit (or one of the culprits) is WowUp. It shows that it is updated the TalentedData folder, but, its data is old.

**Comment by Lethay** [comment]
Talented_Data no longer exists in current releases. You can delete it. I'm surprised WoWUp didn't.

**Comment by Lethay** [comment]
I also notice that WoWUp is indicating "TBC" there. Is it definitely downloading the WotLK version?

**Comment by Dana-Ferguson** [comment]
![image](https://user-images.githubusercontent.com/7284858/188454896-b10c238b-d5be-4825-9ac4-1afdf3f479e5.png)

LOL -- cool -- it is not downloading the correct version. I was just looking into that, it has a broken link for the newest version, and, seems to be picking out an older release for their database.

https://addons.wago.io/addons/talentedclassic/versions?stability=stable

**Comment by Dana-Ferguson** [comment]
(on github) https://github.com/Lethay/TalentedClassic/releases/download/v220904/Talented.zip
(on wowup) https://github.com/Lethay/TalentedClassic/releases/download/v220904-wotlk/Talented.zip

**Comment by Lethay** [comment]
Thanks. Fixed, probably. Still haven't worked out what wago.io is looking for to automatically tag things as WotLK.

**Comment by Dana-Ferguson** [comment]
Nice! I can see that it is fixed. Unfortunately, WowUp is still downloading the wrong version (as before). If I direct WowUp to use the WowUpHub (vs Wago), it works but it downloads the version from a couple days ago (220823) ~ which compared to  210718 ~ is a big improvement, lol. Suppose it might take a bit for their database to update.

**Comment by Lethay** [comment]
The WowUpHub is the TBC version, which is strictly wrong. No idea why wago.io is giving you the wrong version, though. I'll try and look into it in a few hours.
