### ISSUE TITLE
glyph error

### ISSUE THREAD

**Issue by kakkakk** [Lethay/TalentedClassic#77]
happened just after learning minor glyph, Glyph of Raise Dead

6x Talented_GlyphFrame\frame.lua:120: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[string "=[C]"]: in function `PlaySound'
[string "@Talented_GlyphFrame\frame.lua"]:120: in function <Talented_GlyphFrame\frame.lua:111>

Locals:
(*temporary) = "Glyph_MajorCreate"
(*temporary) = "SFX"

**Comment by Lethay** [comment]
Should be fixed with latest release, let me know if not
