### ISSUE TITLE
Talent tree showing "inconsistent" error and points are all in the wrong spots

### ISSUE THREAD

**Issue by omgkielb** [Lethay/TalentedClassic#79]
Since the update 2 hours ago, all my talent are in the completely wrong spots, if i change specs the talent tree basically resets, tested on a bunch of toons even reinstalled and cleared WTF content
![image](https://user-images.githubusercontent.com/31836335/188296867-fe6bba28-24d0-45e9-be58-6aba176a9691.png)
After respec
![image](https://user-images.githubusercontent.com/31836335/188296879-88b73c80-9c80-4bff-b02a-0487dbd5fb04.png)

![image](https://user-images.githubusercontent.com/31836335/188296892-81495cab-1981-4969-96cc-eb0bfbb4142d.png)

**Comment by Lethay** [comment]
Was due to a mild mishap. Fixed now, thanks for reporting fast
