### ISSUE TITLE
Errors while trying to import a template from wowhead etc.

### ISSUE THREAD

**Issue by AutolycusWolf** [Lethay/TalentedClassic#80]
Keep getting this error every time I try to import a template from wowhead

1x Talented\core.lua:150: attempt to index field '?' (a nil value)
[string "@Talented\core.lua"]:150: in function <Talented\core.lua:144>
[string "@Talented\core.lua"]:225: in function `ImportTemplate'
[string "@Talented\ui\menu.lua"]:243: in function `OnAccept'
[string "@FrameXML\StaticPopup.lua"]:5228: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
templates = <table> {
 HUNTER = <table> {
 }
 WARRIOR = <table> {
 }
 ROGUE = <table> {
 }
 MAGE = <table> {
 }
 PRIEST = <table> {
 }
 Tenacity = <table> {
 }
 PALADIN = <table> {
 }
 WARLOCK = <table> {
 }
 SHAMAN = <table> {
 }
 DEATHKNIGHT = <table> {
 }
 DRUID = <table> {
 }
 Ferocity = <table> {
 }
 Cunning = <table> {
 }
}
name = "Imported"
class = "DEATH-KNIGHT"
count = 0
template = <table> {
 name = "Imported"
 class = "DEATH-KNIGHT"
}
(*temporary) = nil
(*temporary) = "Imported"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by Lethay** [comment]
Is this with the latest version? Looks like you have no data on talents in the system

**Comment by AutolycusWolf** [comment]
Latest versions seems to be working seamlessly so far. Thumbs up. Will keep you updated if anything else happens along the way!
