### ISSUE TITLE
talents window not opening

### ISSUE THREAD

**Issue by mev1995** [Lethay/TalentedClassic#85]
whenever i try to open the talent window, i get following error:
Message: Interface\AddOns\Talented\view.lua:315: attempt to index global 'activate' (a function value)
Time: Wed Sep  7 19:21:03 2022
Count: 1
Stack: Interface\AddOns\Talented\view.lua:315: attempt to index global 'activate' (a function value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\Talented\view.lua"]:315: in function `Update'
[string "@Interface\AddOns\Talented\view.lua"]:140: in function `SetClass'
[string "@Interface\AddOns\Talented\view.lua"]:163: in function <Interface\AddOns\Talented\view.lua:143>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Talented\core.lua"]:276: in function `SetTemplate'
[string "@Interface\AddOns\Talented\core.lua"]:380: in function `Update'
[string "@Interface\AddOns\Talented\core.lua"]:363: in function <Interface\AddOns\Talented\core.lua:360>
[string "=(tail call)"]: ?
[string "=[C]"]: ?

Locals: errMsg = "Interface\AddOns\Talented\view.lua:315: attempt to index global 'activate' (a function value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Lethay** [comment]
Do you have Scrolling Loot Text? There is a bug in that addon that causes this.

**Comment by Lethay** [comment]
If this was your issue, this interaction should've now been fixed.

**Comment by mev1995** [comment]
i did indeed have scrolling loot text

**Comment by mev1995** [comment]
deactivating scrolling loot text fixed it, thank you

**Comment by Lethay** [comment]
In addition, it should now work with scrolling loot text too!
